### ISSUE TITLE
email duplikat

### ISSUE THREAD

**Issue by perkedrcl** [perkedrcl/MapPrint#1]
stavili smo unikat i on mi salje greska u kodu connections.php line 713 i jos brda eve i skrinsot

![screenshot from 2016-08-11 16-13-59](https://cloud.githubusercontent.com/assets/20441473/17591577/11414f96-5fdf-11e6-8dc4-86f0589b6eb6.png)

**Comment by djuka038** [comment]
Pažljivo pogledj kod kada ovo uradim samo si u suštini trebao da ceo kod da staviš u try/catch
